package com.fbp.engine.engine;

import com.fbp.engine.core.*;
import com.fbp.engine.core.Flow.FlowState;
import com.fbp.engine.node.AbstractNode;
import com.fbp.engine.parser.*;
import com.fbp.engine.registry.NodeRegistry;
import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class FlowManager {
    @Getter
    private final FlowEngine engine;
    private final NodeRegistry nodeRegistry;
    private final Map<String, FlowParser> parsers = new HashMap<>();
    private final Map<String, Flow> managedFlows = new ConcurrentHashMap<>();

    public FlowManager(FlowEngine engine, NodeRegistry nodeRegistry) {
        this.engine = engine;
        this.nodeRegistry = nodeRegistry;
    }

    public void addParser(FlowParser parser) {
        parsers.put(parser.getSupportedFormat().toLowerCase(), parser);
    }

    /**
     * [기존 방식] InputStream을 통해 배포
     */
    public String deploy(String format, InputStream inputStream) {
        FlowParser parser = parsers.get(format.toLowerCase());
        if (parser == null) {
            throw new RuntimeException("지원하지 않는 포맷: " + format);
        }

        FlowDefinition def = parser.parse(inputStream);
        return deploy(def);
    }

    /**
     * [새로운 방식] FlowDefinition 설계도를 직접 받아 배포 수행
     */
    public String deploy(FlowDefinition def) {
        def.validate();

        // 2. 기존 동일 ID 플로우가 있다면 제거 및 자원 해제
        if (managedFlows.containsKey(def.id())) {
            this.remove(def.id()); // MDC.remove와의 충돌 방지를 위해 this 명시
        }

        // 3. 설계도를 바탕으로 Flow 조립 (노드 생성 및 커넥션 주입)
        Flow flow = assembleFlow(def);

        // 4. 엔진 등록 및 가동
        engine.register(flow);
        engine.startFlow(flow.getId());
        managedFlows.put(flow.getId(), flow);

        log.info("[FlowManager] 플로우 배포 완료: {}", flow.getId());
        return flow.getId();
    }

    /**
     * NodeRegistry와 ConnectionFactory를 사용하여 실제 Flow 객체를 조립합니다.
     */
    private Flow assembleFlow(FlowDefinition def) {
        Flow flow = new Flow(def.id());

        // A. NodeRegistry를 통한 노드 인스턴스 생성
        for (NodeDefinition nodeDef : def.nodes()) {
            AbstractNode node = (AbstractNode) nodeRegistry.create(
                    nodeDef.type(),
                    nodeDef.id(),
                    nodeDef.config()
            );
            flow.addNode(node);
        }

        for (ConnectionDefinition connDef : def.connections()) {
            // 예: "timer:out->log:in"
            String autoGeneratedId = String.format("%s->%s", connDef.from(), connDef.to());

            // MQTT 토픽 생성 (기존 로직 유지)
            String topic = String.format("fbp/%s/%s",
                    def.id(),
                    autoGeneratedId.replace(":", ".").replace("->", "_"));

            // ConnectionFactory에 자동 생성된 ID 전달
            Connection conn = ConnectionFactory.create(
                    autoGeneratedId,
                    def.transport(),
                    topic
            );

            // 노드 및 포트 파싱 후 연결
            String[] fromParts = connDef.from().split(":");
            String[] toParts = connDef.to().split(":");
            flow.connect(fromParts[0], fromParts[1], toParts[0], toParts[1], conn);
        }

        return flow;
    }

    public void remove(String flowId) {
        Flow flow = managedFlows.get(flowId);
        if (flow == null) return;

        if (flow.getFlowState().equals(FlowState.RUNNING)) {
            engine.stopFlow(flowId);
            // 자원 해제 (MQTT unsubscribe 등)
            flow.getConnections().forEach(Connection::close);
        }
        engine.unRegister(flow);
        managedFlows.remove(flowId);
    }

    public void addNode(String flowId, NodeDefinition def) {
        Flow flow = managedFlows.get(flowId);
        if(flow == null) throw new FlowNotFoundException(flowId);

        AbstractNode newNode = (AbstractNode) nodeRegistry.create(def.type(), def.id(), def.config());

        flow.addNode(newNode);
        newNode.initialize();

        System.out.println("[" + def.id() + "] 노드가 성공적으로 추가되었습니다.");
    }

    public void removeNode(String flowId, String nodeId) {
        Flow flow = managedFlows.get(flowId);
        if(flow == null) return;

        AbstractNode node = flow.getNode(nodeId);
        if(node != null) {
            node.shutdown();
            flow.removeNodeWithConnections(nodeId);
            System.out.println("[" + nodeId + "] 노드 제거");
        }
    }

    /**
     * 커넥션 추가 명령어 처리
     * @param flowId   플로우 ID
     * @param fromStr  출발지 정보 (예: "timer:out")
     * @param toStr    목적지 정보 (예: "logger:in")
     */
    public void addConnection(String flowId, String fromStr, String toStr) {
        Flow flow = managedFlows.get(flowId);
        if (flow == null) {
            System.err.println("해당 플로우를 찾을 수 없습니다: " + flowId);
            return;
        }

        try {
            // 1. 문자열 파싱 (":" 기준으로 분리)
            String[] fromParts = fromStr.split(":");
            String[] toParts = toStr.split(":");

            if (fromParts.length != 2 || toParts.length != 2) {
                throw new IllegalArgumentException("입력 형식이 올바르지 않습니다. (예: nodeId:port)");
            }

            String sourceNodeId = fromParts[0];
            String sourcePort = fromParts[1];
            String targetNodeId = toParts[0];
            String targetPort = toParts[1];

            // 2. Flow 클래스의 connect 호출 (실제 Connection 객체 생성 및 포트 등록)
            flow.connect(sourceNodeId, sourcePort, targetNodeId, targetPort);

            System.out.println(String.format("[연결 성공] %s (%s) -> %s (%s)",
                    sourceNodeId, sourcePort, targetNodeId, targetPort));

        } catch (IllegalArgumentException e) {
            System.err.println("연결 실패: " + e.getMessage());
        } catch (Exception e) {
            System.err.println("오류 발생: " + e.getMessage());
        }
    }

    public void removeConnection(String flowId, String connectionId) {
        Flow flow = managedFlows.get(flowId);
        if (flow == null) return;

        // 플로우에게 ID를 줄 테니 알아서 안전하게 끊으라고 시킵니다.
        flow.removeConnection(connectionId);

        System.out.println("[Connection 제거 완료] ID: " + connectionId);
    }

    public void applyPatch(String flowId, FlowDefinition newDef) {
        Flow currentFlow = managedFlows.get(flowId);
        if (currentFlow == null) return;

        // 0. 설계도 유효성 검사
        newDef.validate();

        Map<String, AbstractNode> oldNodes = currentFlow.getNodes();
        Map<String, NodeDefinition> newNodes = newDef.getNodeMap();

        List<String> nodesToRemove = oldNodes.keySet().stream()
                .filter(id -> !newNodes.containsKey(id)).toList();
        List<NodeDefinition> nodesToAdd = newNodes.values().stream()
                .filter(def -> !oldNodes.containsKey(def.id())).toList();
        List<NodeDefinition> nodesToUpdate = newNodes.values().stream()
                .filter(def -> oldNodes.containsKey(def.id()))
                // 설정(Map)이 바뀐 경우만 필터링
                .filter(def -> !oldNodes.get(def.id()).getConfig().equals(def.config()))
                .toList();

        List<Connection> oldConns = currentFlow.getConnections();
        Set<String> newConnids = newDef.getConnectionIds();

        List<String> connsToRemove = oldConns.stream()
                .map(Connection::getId)
                .filter(id -> !newConnids.contains(id)).toList();

        List<ConnectionDefinition> connsToAdd = newDef.connections().stream()
                .filter(nc -> oldConns.stream().noneMatch(oc -> oc.getId().equals(nc.toAutoId()))).toList();

        connsToRemove.forEach(currentFlow::removeConnection);
        nodesToRemove.forEach(id -> this.removeNode(flowId, id));
        nodesToAdd.forEach(def -> this.addNode(flowId, def));

        nodesToUpdate.forEach(def -> {
            AbstractNode node = currentFlow.getNode(def.id());
            if (node != null) {
                node.reconfigure(def.config());
                System.out.println("[" + def.id() + "] 설정 업데이트 완료.");
            }
        });

        connsToAdd.forEach(nc -> {
            String[] from = nc.from().split(":");
            String[] to = nc.to().split(":");
            currentFlow.connect(from[0], from[1], to[0], to[1]);
        });

        System.out.println("[" + flowId + "] 패치 적용 성공.");
    }

    public FlowState getStatus(String flowId) {
        Flow flow = managedFlows.get(flowId);
        if(flow == null) {
            throw new FlowNotFoundException("존재하지 않는 Flow");
        }

        return flow.getFlowState();
    }

    public List<Flow> list() {
        return managedFlows.values().stream().toList();
    }

    public List<Flow> getRunningFlows() {
        return managedFlows.values().stream()
                .filter(flow -> flow.getFlowState().equals(FlowState.RUNNING))
                .toList();
    }

    public void stop(String flowId) {
        Flow flow = managedFlows.get(flowId);

        if(flow == null) {
            throw new FlowNotFoundException("존재하지 않는 Flow");
        }

        if(flow.getFlowState().equals(FlowState.RUNNING)) {
            engine.stopFlow(flowId);
        }
    }

    public void restart(String flowId) {
        Flow flow = managedFlows.get(flowId);

        if(flow == null) {
            throw new FlowNotFoundException("존재하지 않는 Flow");
        }
        if(flow.getFlowState().equals(FlowState.STOPPED)) {
            engine.startFlow(flowId);
        }
    }
}
