package com.fbp.engine.engine;

import com.fbp.engine.core.*;
import com.fbp.engine.core.Flow.FlowState;
import com.fbp.engine.metrics.event.FlowEvent;
import com.fbp.engine.node.AbstractNode;
import com.fbp.engine.parser.*;
import com.fbp.engine.registry.NodeRegistry;
import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;

/**
 * FlowManager는 FBP 엔진에서 플로우(Flow)의 전체 생명주기를 관리하는 매니저 클래스입니다.
 * JSON 등 외부 설정(FlowDefinition)을 파싱하여 실제 노드(Node)와 연결(Connection)을 조립(Assemble)하고,
 * 엔진에 등록하여 실행/중지/삭제 및 런타임 동적 패치(Hot Patch)를 수행합니다.
 */
@Slf4j
public class FlowManager {
    @Getter
    private final FlowEngine engine;
    private final NodeRegistry nodeRegistry;
    private final Map<String, FlowParser> parsers = new HashMap<>();
    private final Map<String, Flow> managedFlows = new ConcurrentHashMap<>();

    public FlowManager(FlowEngine engine, NodeRegistry nodeRegistry) {
        this.engine = engine;
        this.nodeRegistry = nodeRegistry;
    }

    public void addParser(FlowParser parser) {
        parsers.put(parser.getSupportedFormat().toLowerCase(), parser);
    }

    /**
     * InputStream을 통해 특정 포맷의 플로우 정의를 읽어와 엔진에 배포합니다.
     * @param format 파일 포맷 (예: "json")
     * @param inputStream 플로우 설계도가 담긴 입력 스트림
     * @return 배포된 플로우의 ID
     */
    public String deploy(String format, InputStream inputStream) {
        FlowParser parser = parsers.get(format.toLowerCase());
        if (parser == null) {
            throw new RuntimeException("지원하지 않는 포맷: " + format);
        }

        FlowDefinition def = parser.parse(inputStream);
        return deploy(def);
    }

    /**
     * FlowDefinition 객체를 직접 전달받아 플로우를 조립하고 엔진에 등록합니다.
     * 동일한 ID의 플로우가 이미 존재할 경우, 기존 플로우를 안전하게 제거한 뒤 재배포합니다.
     * @param def 플로우 정의 설계도
     * @return 배포된 플로우의 ID
     */
    public String deploy(FlowDefinition def) {
        def.validate();

        // 2. 기존 동일 ID 플로우가 있다면 제거 및 자원 해제
        if (managedFlows.containsKey(def.id())) {
            this.remove(def.id()); // MDC.remove와의 충돌 방지를 위해 this 명시
        }

        // 3. 설계도를 바탕으로 Flow 조립 (노드 생성 및 커넥션 주입)
        Flow flow = assembleFlow(def);

        // 4. 엔진 등록
        engine.register(flow, def);
        managedFlows.put(flow.getId(), flow);

        submitEvent(def.id(), "DEPLOY", "Flow deployed: " + def.name());

        log.info("[FlowManager] 플로우 배포 완료: {}", flow.getId());
        return flow.getId();
    }

    private void submitEvent(String flowId, String type, String summary) {
        if (engine.getCollector() != null) {
            engine.getCollector().submit(new FlowEvent(System.currentTimeMillis(), flowId, type, summary));
        }
    }

    /**
     * 설계도(FlowDefinition)에 정의된 노드와 연결 정보를 바탕으로 실제 Flow 객체를 빌드합니다.
     * @param def 플로우 정의 객체
     * @return 조립이 완료된 Flow 인스턴스
     */
    private Flow assembleFlow(FlowDefinition def) {
        Flow flow = new Flow(def.id());

        // A. NodeRegistry를 통한 노드 인스턴스 생성
        for (NodeDefinition nodeDef : def.nodes()) {
            AbstractNode node = (AbstractNode) nodeRegistry.create(
                    nodeDef.type(),
                    nodeDef.id(),
                    nodeDef.config()
            );
            flow.addNode(node);
        }

        for (ConnectionDefinition connDef : def.connections()) {
            // 예: "timer:out->log:in"
            String autoGeneratedId = String.format("%s->%s", connDef.from(), connDef.to());

            // MQTT 토픽 생성 (기존 로직 유지)
            String topic = String.format("fbp/%s/%s",
                    def.id(),
                    autoGeneratedId.replace(":", ".").replace("->", "_"));

            // ConnectionFactory에 자동 생성된 ID 전달
            Connection conn = ConnectionFactory.create(
                    autoGeneratedId,
                    def.transport(),
                    topic
            );

            // 노드 및 포트 파싱 후 연결
            String[] fromParts = connDef.from().split(":");
            String[] toParts = connDef.to().split(":");
            flow.connect(fromParts[0], fromParts[1], toParts[0], toParts[1], conn);
        }

        return flow;
    }

    /**
     * 등록된 플로우를 엔진에서 제거하고 관련 자원(MQTT 구독 등)을 모두 해제합니다.
     * @param flowId 제거할 플로우 ID
     */
    public void remove(String flowId) {
        Flow flow = managedFlows.get(flowId);
        if (flow == null) {
            throw new FlowNotFoundException("존재하지 않는 Flow: " + flowId);
        }

        if (flow.getFlowState().equals(FlowState.RUNNING)) {
            engine.stopFlow(flowId);
            // 자원 해제 (MQTT unsubscribe 등)
            flow.getConnections().forEach(Connection::close);
        }
        engine.unRegister(flow);
        managedFlows.remove(flowId);
        submitEvent(flowId, "REMOVE", "Flow removed");
    }

    /**
     * 실행 중인 플로우를 중단하지 않고 동적으로 노드를 추가합니다.
     * @param flowId 대상 플로우 ID
     * @param def 추가할 노드의 설계 정보
     */
    public void addNode(String flowId, NodeDefinition def) {
        Flow flow = managedFlows.get(flowId);
        if(flow == null) throw new FlowNotFoundException(flowId);

        AbstractNode newNode = (AbstractNode) nodeRegistry.create(def.type(), def.id(), def.config());

        flow.addNode(newNode);
        newNode.initialize();

        submitEvent(flowId, "ADD_NODE", "Node added: " + def.id());
        System.out.println("[" + def.id() + "] 노드가 성공적으로 추가되었습니다.");
    }

    /**
     * 실행 중인 플로우에서 특정 노드를 동적으로 제거합니다.
     * @param flowId 대상 플로우 ID
     * @param nodeId 제거할 노드 ID
     */
    public void removeNode(String flowId, String nodeId) {
        Flow flow = managedFlows.get(flowId);
        if(flow == null) return;

        AbstractNode node = flow.getNode(nodeId);
        if(node != null) {
            node.shutdown();
            flow.removeNodeWithConnections(nodeId);
            submitEvent(flowId, "REMOVE_NODE", "Node removed: " + nodeId);
            System.out.println("[" + nodeId + "] 노드 제거");
        }
    }

    /**
     * 실행 중인 플로우에 새로운 연결(Wire)을 동적으로 추가합니다.
     * @param flowId 대상 플로우 ID
     * @param fromStr 소스 정보 (예: "sensor:out")
     * @param toStr 타겟 정보 (예: "rule:in")
     */
    public void addConnection(String flowId, String fromStr, String toStr) {
        Flow flow = managedFlows.get(flowId);
        if (flow == null) {
            System.err.println("해당 플로우를 찾을 수 없습니다: " + flowId);
            return;
        }

        try {
            String[] fromParts = fromStr.split(":");
            String[] toParts = toStr.split(":");

            if (fromParts.length != 2 || toParts.length != 2) {
                throw new IllegalArgumentException("입력 형식이 올바르지 않습니다. (예: nodeId:port)");
            }

            String sourceNodeId = fromParts[0];
            String sourcePort = fromParts[1];
            String targetNodeId = toParts[0];
            String targetPort = toParts[1];

            flow.connect(sourceNodeId, sourcePort, targetNodeId, targetPort);

            submitEvent(flowId, "ADD_WIRE", "Wire added: " + fromStr + " -> " + toStr);
            System.out.println(String.format("[연결 성공] %s (%s) -> %s (%s)",
                    sourceNodeId, sourcePort, targetNodeId, targetPort));

        } catch (IllegalArgumentException e) {
            System.err.println("연결 실패: " + e.getMessage());
        } catch (Exception e) {
            System.err.println("오류 발생: " + e.getMessage());
        }
    }

    /**
     * 실행 중인 플로우에서 특정 연결을 동적으로 끊습니다.
     * @param flowId 대상 플로우 ID
     * @param connectionId 제거할 연결의 자동 생성된 ID
     */
    public void removeConnection(String flowId, String connectionId) {
        Flow flow = managedFlows.get(flowId);
        if (flow == null) return;

        flow.removeConnection(connectionId);

        submitEvent(flowId, "REMOVE_WIRE", "Wire removed: " + connectionId);
        System.out.println("[Connection 제거 완료] ID: " + connectionId);
    }

    /**
     * 플로우 핫 패치: 새로운 설계도를 받아 현재 실행 중인 플로우와의 차이점을 계산하고,
     * 변경된 노드/연결/설정만 선별적으로 업데이트합니다.
     * @param flowId 대상 플로우 ID
     * @param newDef 새로운 설계도 객체
     */
    public void applyPatch(String flowId, FlowDefinition newDef) {
        Flow currentFlow = managedFlows.get(flowId);
        if (currentFlow == null) return;

        newDef.validate();

        Map<String, AbstractNode> oldNodes = currentFlow.getNodes();
        Map<String, NodeDefinition> newNodes = newDef.getNodeMap();

        List<String> nodesToRemove = oldNodes.keySet().stream()
                .filter(id -> !newNodes.containsKey(id)).toList();
        List<NodeDefinition> nodesToAdd = newNodes.values().stream()
                .filter(def -> !oldNodes.containsKey(def.id())).toList();
        List<NodeDefinition> nodesToUpdate = newNodes.values().stream()
                .filter(def -> oldNodes.containsKey(def.id()))
                .filter(def -> !oldNodes.get(def.id()).getConfig().equals(def.config()))
                .toList();

        List<Connection> oldConns = currentFlow.getConnections();
        Set<String> newConnids = newDef.getConnectionIds();

        List<String> connsToRemove = oldConns.stream()
                .map(Connection::getId)
                .filter(id -> !newConnids.contains(id)).toList();

        List<ConnectionDefinition> connsToAdd = newDef.connections().stream()
                .filter(nc -> oldConns.stream().noneMatch(oc -> oc.getId().equals(nc.toAutoId()))).toList();

        connsToRemove.forEach(currentFlow::removeConnection);
        nodesToRemove.forEach(id -> this.removeNode(flowId, id));
        nodesToAdd.forEach(def -> this.addNode(flowId, def));

        nodesToUpdate.forEach(def -> {
            AbstractNode node = currentFlow.getNode(def.id());
            if (node != null) {
                node.reconfigure(def.config());
                System.out.println("[" + def.id() + "] 설정 업데이트 완료.");
            }
        });

        connsToAdd.forEach(nc -> {
            String[] from = nc.from().split(":");
            String[] to = nc.to().split(":");
            currentFlow.connect(from[0], from[1], to[0], to[1]);
        });

        submitEvent(flowId, "PATCH", "Flow definition patched");
        System.out.println("[" + flowId + "] 패치 적용 성공.");
    }

    public FlowState getStatus(String flowId) {
        Flow flow = managedFlows.get(flowId);
        if(flow == null) {
            throw new FlowNotFoundException("존재하지 않는 Flow");
        }

        return flow.getFlowState();
    }

    public List<Flow> list() {
        return managedFlows.values().stream().toList();
    }

    public List<Flow> getRunningFlows() {
        return managedFlows.values().stream()
                .filter(flow -> flow.getFlowState().equals(FlowState.RUNNING))
                .toList();
    }

    /**
     * 플로우의 메시지 처리를 중단하고 노드들을 정지 상태로 전환합니다.
     * @param flowId 중지할 플로우 ID
     */
    public void stop(String flowId) {
        Flow flow = managedFlows.get(flowId);

        if(flow == null) {
            throw new FlowNotFoundException("존재하지 않는 Flow");
        }

        if(flow.getFlowState().equals(FlowState.RUNNING)) {
            engine.stopFlow(flowId);
            submitEvent(flowId, "STOP", "Flow stopped");
        }
    }

    /**
     * 정지된 플로우를 다시 가동하거나, 시작합니다.
     * @param flowId 시작할 플로우 ID
     */
    public void restart(String flowId) {
        Flow flow = managedFlows.get(flowId);

        if(flow == null) {
            throw new FlowNotFoundException("존재하지 않는 Flow");
        }
        if(flow.getFlowState().equals(FlowState.STOPPED)) {
            engine.startFlow(flowId);
            submitEvent(flowId, "START", "Flow started/restarted");
        }
    }
}

